export class View{

    idTransfo: number 
    oPe: string 
    oTe: number 
    observaciones: string 
    rangoInicio: number 
    rangoFin: number 
    idCliente?: number
    nombreCli: string 
    potencia: number 
    idTipoTransfo?: number
    anio:number;
    mes:number;
    prioridad:number;
    documentacion: Date 
    docTiempoParc: string 
    bobinaBT1: Date 
    bBT1TiempoParc: string 
    bobinaBT2: Date 
    bBT2TiempoParc: string 
    bobinaBT3: Date 
    bBT3TiempoParc: string 
    bobinaAT1: Date 
    bAT1TiempoParc: string 
    bobinaAT2: Date 
    bAT2TiempoParc: string 
    bobinaAT3: Date 
    bAT3TiempoParc: string 
    bobinaRG1: Date 
    bRG1TiempoParc: string 
    bobinaRG2: Date 
    bRG2TiempoParc: string 
    bobinaRG3: Date 
    bRG3TiempoParc: string 
    bobinaRF1: Date 
    bRF1TiempoParc: string 
    bobinaRF2: Date 
    bRF2TiempoParc: string 
    bobinaRF3: Date 
    bRF3TiempoParc: string 
    ensamblajeBobinas: Date 
    ensBobTiempoParc: string 
    corteYPlegadoPYS: Date 
    cYPTiempoParc: string 
    soldaduraPYS: Date 
    solTiempoParc: string 
    envioPYS: Date 
    envTiempoParc: string 
    nucleo: Date 
    nucleoTiempoParc: string 
    montaje: Date 
    montajeTiempoParc: string 
    horno: Date 
    hornoTiempoParc: string 
    cYPTapaCuba: Date 
    cYPTCTiempoParc: string 
    tapa: Date 
    tapaTiempoParc: string 
    radiadoresOPaneles: Date 
    rOPTiempoParc: string 
    cuba: Date 
    cubaTiempoParc: string 
    tintasPenetrantes: Date 
    tPTiempoParc: string 
    granallado: Date 
    granalladoTiempoParc: string 
    pintura: Date 
    pinturaTiempoParc: string 
    encubado: Date 
    encubadoTiempoParc: string 
    ensayosRef: Date 
    eRefTiempoParc: string 
    terminacion: Date 
    terminacionTiempoParc: string 
    envioADeposito: Date 
    eADepTiempoParc: string 
    envioACliente: Date 
    eACliTiempoParc: string 

}